name: 'Repo Lockdown'

on:
  #issues:
    #types: opened
  pull_request_target:
    types: opened
  #schedule:
    #- cron: '* */6 * * *'

permissions:
  #issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          pr-comment: >
            This repository does not accept pull requests,
            see the README.md for details.
          skip-closed-pr-comment: true
